# Austin Johnson
# Partner: Hunter Booth
# CPSC 3220
# Project 4
# Makefile

CFLAGS = -Wall -g

all: notjustcats

notjustcats: notjustcats.c
	gcc $(CFLAGS) -o notjustcats file.c notjustcats.c

clean :
	rm notjustcats
